additionalRepositories:
  - url: https://github.com/adamzero1/docker-magento.git
    checkoutLocation: rde

tasks:
  - name: Pull in RDE
    # TODO - change to 'offical' fork
    # This could then be branched/versioned per Magento release
    before: >
      cd /workspace/rde 
      && git fetch 
      && git switch mage-os-rde 
      && gp sync-done rde-repo-setup
      && exit

  - name: Fix File Permissions (Temp until issue resolved propperly)
    before: chmod -R a+rw /workspace/magento2 && exit

  - name: Start Stack
    init: >
      gp sync-await rde-repo-setup
      && /workspace/rde/compose/bin/init
      && gp sync-done magento-installed
      && exit
  
  - name: indexer:reindex
    init: gp sync-await magento-installed
    command: /workspace/rde/compose/bin/clinotty bin/magento indexer:reindex && exit
  
  - name: Fix socket permissions (Temp until issue resolved propperly)
    init: gp sync-await magento-installed
    command: >
      docker exec -u root phpfpm bash -c "chmod a+rwx /sock/docker.sock; ls -lath /sock/docker.sock"
      && gp sync-done socket-permissions-resolved
      && exit

  - name: Magento Init
    init: gp sync-await magento-installed
    command: >
      /workspace/rde/compose/bin/clinotty bin/magento deploy:mode:set developer 
      && /workspace/rde/compose/bin/clinotty bin/magento cache:enable 
      && /workspace/rde/compose/bin/clinotty bin/magento cache:flush 
      && gp sync-await socket-permissions-resolved
      # Hit frontend to generate static symlinks (and to check site is up)
      && RESPONSE_CODE=$(curl -s -o /dev/null -w '%{http_code}' $(gp url 443)); if [ ${RESPONSE_CODE} -eq "201" ]; then echo "all good"; exit; else echo "There was an issue when requesting the frontend, please see: $(gp url 443)"; fi
  
  - name: Install Magento cron
    init: gp sync-await magento-installed
    command: /workspace/rde/compose/bin/clinotty bin/magento cron:install && exit

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: Frontend
    description: Frontend URL of Magento
    port: 443
    onOpen: open-browser
    visibility: public
  - name: Http Traffic
    description: Http traffic (shouldnt be used)
    port: 80
    visibility: private
    onOpen: ignore
  - name: db
    description: Database port
    port: 3306
    visibility: private
    onOpen: ignore
  - name: Redis
    description: Redis port
    port: 6379
    visibility: private
    onOpen: ignore
  - name: Elasticsearch API
    description: Elasticsearch API port
    port: 9200
    visibility: private
    onOpen: ignore
  - name: Elasticsearch Cluster Comms
    description: Elasticsearch search cluster communication port
    port: 9300
    visibility: private
    onOpen: ignore
  - name: RabbitMQ Management
    description: RabbitMQ management port
    port: 15672
    visibility: private
    onOpen: ignore
  - name: RabbitMQ Comms
    description: RabbitMQ communiation port
    port: 5672
    visibility: private
    onOpen: ignore
  - name: Mailcatcher
    description: Mailcatcher port
    port: 1080
    visibility: private
    onOpen: ignore
  - name: PHP My Admin
    description: PHPMyAdmin port
    port: 8080
    visibility: private
    onOpen: ignore
  
