name: Unit Tests

on:
  pull_request:
    branches:
      - 2.4-develop
      - nx-work

permissions:
  contents: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run Unit Tests
        uses: adamzero1/temp-repo2/blob/main/.github/workflows/mageos-unit-tests.yml@main